version: '3.8'

services:
  db:
    image: dockingbay/rdkit-postgresql:latest
    container_name: toxichem-db
    environment:
      POSTGRES_DB: toxichem
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: toxichem-redis
    restart: unless-stopped

  backend:
    build: .
    container_name: toxichem-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/toxichem
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: toxichem-worker
    command: celery -A workers.celery_app.celery_app worker -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/toxichem
      REDIS_URL: redis://redis:6379
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: toxichem-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_

prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana