openapi: 3.0.0
info:
  title: ToxiChem LabSuite API
  version: 2.0.0
paths:
  /predict/toxicity:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                smiles: { type: string }
      responses:
        '200':
          description: Toxicity predictions